### PR TITLE
[FBTLOPS-91] Install into Kubernetes

### PR DESCRIPTION
**Pull request by mralexandernickel**
Containerize Application.
Add Makefile for easier build and publish of OCI-Image.
Add Helm-Chart for easy installation into K8S-cluster.
Remove "techradar"-subdirectory to have it clean.

### CODE REVIEW

**Comment by mralexandernickel** [comment]
https://technology-radar.flagbit.cloud/

**Comment by AngelVazquezArroyo** [comment]
Is planed to create the Docker Images automatically somehow? Like I see, now should be created manually :(

**Comment by mralexandernickel** [comment]
Thats the question... right now there is a travis.yml inside the repository, so I am unsure if it s planne to use travis here. but the phrase "manually" is also not really correct, it's just a matter calling some commands from the Makefile 😅

**Comment by mralexandernickel** [comment]
... in fact it's just ONE command... `make publish` that's it 😊

**Review by AngelVazquezArroyo — APPROVED** [review]
LGTM

**Review by jjoshm — APPROVED** [review]
LGTM

**Pull request merged**
